version: '3.8'

services:
  app:
    build: .
    container_name: post-app
    ports:
      - "3030:3030"
    environment:
      GIN_MODE: "release"
      LISTEN_ADDRESS: "0.0.0.0:3030"
      DATABASE_DSN: "host=db user=postgres password=postgres dbname=post port=5432 sslmode=disable TimeZone=Asia/Bangkok"
      CORS_ALLOW_ORIGIN: "*"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:14.1-alpine
    container_name: post-db
    restart: always
    environment:
      POSTGRES_DB: post
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
  adminer:
    image: adminer
    container_name: post-adminer
    restart: always
    ports:
      - 3031:8080
    depends_on:
      - db
    links:
      - db
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
